examples
example
	^ self new
		name: 'Visitando el lugar';
		goal:
			'1) Brindar una nueva experiencia que permita “aprender juntos”; 2) Estimular la curiosidad para promover el aprendizaje';
		performanceIndicator:
			'a) Los alumnos recopilan informacion no repetida y realizan el registro de explicaciones, fotografias, se se acercan a la recepcion a solicitar informacion, b) Durante el recorrido, la mayoria de los alumnos cuestiona en forma constante con preguntas elaboradas, responden a las preguntas realizadas por el guia o, expresan respuestas anticipadas a la experiencia, c) Los alumnos demuestran atencion, estos conversan sobre los temas a abordar durante el traslado al lugar, d) No se observa gran dispersion del grupo, se observa un grupo organizado, ordenado y con buena relacion, e) Los alumnos manipulan los dispositivos f) todos los alumnos pueden contar experiencias donde fue protagonista';
		rationale:
			'En muchas ocasiones, el alumno no alcanza a distinguir la aplicación práctica o, la importancia de lo enseñado en la escuela, para su realidad. Esto, los lleva a estudiar de memoria, sin relación ninguna y, al desánimo. Por tal motivo, es necesario facilitar la relación entre los estudiantes y los contenidos, permitiendo que el aprendizaje se lleve a cabo, de forma más directa.  El recorrido es un recurso que posibilita la demostración de los contenidos conceptuales, a una experiencia concreta. Las visitas a contextos no formales brindan la oportunidad de aprender en un ambiente de participacion,que promueve, el desarrollo de actitudes positivas, el pensamiento colectivo y el intercambio. La convivencia colectiva, a través de experiencias llevadas a cabo en otros contextos no formales, complementa las actividades educativas de la escuela, amplían el  interés y contribuyen al aprendizaje.';
		addActivity: VisitActivity example;
		yourself